organization: nicks-world
components:
  - repo: cicd-poc-app-1
    codebase: java11
    status: active
  - repo: cicd-poc-app-2
    codebase: java11
    status: active
test-environments:
  - qa
  - uat
  - stg