organization: hippyod
components:
  - repo: cicd-poc-app-1
    codebase: java11
    status: active
  - repo: cicd-poc-app-2
    codebase: java11
    status: active
environments:
  - dev
  - qa
  - uat
  - stg
  - prod