organization: hippyod
team: team-b
branch: development
components:
  - repo: cicd-poc-app-1
    codebase: java11
    status: active
  - repo: cicd-poc-app-2
    codebase: node16
    status: active
dev:
  name: dev
  size: small
prod:
  name: prod
  size: large
test-environments:
  qa:
    name: qa
    size: medium
  uat:
    name: uat
    size: medium
  stg:
    name: stg
    size: medium