organization: nicks-world
team: teamb
components:
  - repo: cicd-poc-app-1b
    codebase: java11
    status: active
  - repo: cicd-poc-app-2b
    codebase: node16
    status: active
    overrides:
      test: jest
test-environments:
  - qa
  - uat
  - stg