organization: nicks-world
team: teama
components:
  - repo: cicd-poc-app-1
    codebase: java11
    status: active
  - repo: cicd-poc-app-2
    codebase: node16
    status: active
    overrides:
      test: jest
test-environments:
  - qa
  - uat
  - stg