name: build-component
on:
  push:
    branch: development
  workflow_dispatch:
jobs:
  build-and-deploy:
    uses: nicks-world/cicd-manager/.github/workflows/build-and-deploy.yml@main
    with:
      system-name: %SYSTEM_NAME%