
#!/usr/bin/bash

set -ex
SYSTEM_DEFS_FILE=$(ls ${SYSTEM_DEFS_DIR}/${SYSTEM_NAME}.y*)
echo "SYSTEM_DEFS_FILE=${SYSTEM_DEFS_FILE}" >> ${GITHUB_ENV}

TEAM_NAME=$(yq '.team' "${SYSTEM_DEFS_FILE}")
echo "TEAM_NAME: ${TEAM_NAME}"
echo "TEAM_NAME=${TEAM_NAME}" >> ${GITHUB_ENV}

DEV_BRANCH=$(yq '.branch' "${SYSTEM_DEFS_FILE}")
echo "DEV_BRANCH: ${DEV_BRANCH}"
echo "DEV_BRANCH=${DEV_BRANCH}" >> ${GITHUB_ENV}

REPO_NAMES=$(yq '[.organization + "/" + .components[].repo]' "${SYSTEM_DEFS_FILE}" -o json)
echo "REPO_NAMES: ${REPO_NAMES}"
echo "REPO_NAMES=${REPO_NAMES}" >> ${GITHUB_ENV}

DEV_ENVIRONMENT=$(yq '.dev.name' "${SYSTEM_DEFS_FILE}")
echo "DEV_ENVIRONMENT: ${DEV_ENVIRONMENT}"
echo "DEV_ENVIRONMENT=${DEV_ENVIRONMENT}" >> ${GITHUB_ENV}

DEV_RESOURCEQUOTA=$(yq '.dev.size' "${SYSTEM_DEFS_FILE}")
echo "DEV_RESOURCEQUOTA: ${DEV_RESOURCEQUOTA}"
echo "DEV_RESOURCEQUOTA=${DEV_RESOURCEQUOTA}" >> ${GITHUB_ENV}

TEST_ENVIRONMENTS=$(yq '.test-environments | keys' "${SYSTEM_DEFS_FILE}" -o json)
echo "TEST_ENVIRONMENTS: ${TEST_ENVIRONMENTS}"
echo "TEST_ENVIRONMENTS=${TEST_ENVIRONMENTS}" >> ${GITHUB_ENV}

TEST_RESOURCEQUOTAS=$(yq '[.test-environments.*]' "${SYSTEM_DEFS_FILE}" -o json)
echo "TEST_RESOURCEQUOTAS: ${TEST_RESOURCEQUOTAS}"
echo "TEST_RESOURCEQUOTAS=${TEST_RESOURCEQUOTAS}" >> ${GITHUB_ENV}

set +ex