name: build-and-deploy
on:
  workflow_call:
    inputs:
      env-to:
        required: false
        type: string
jobs:
  build-test-scan-to-image:
    outputs:
      matrix: ${{ steps.collect-envs.outputs.matrix }}
    runs-on: dev.mdw.nicks.world
    steps:
    - id: setup-environment
      name: setup-environment
      run: |
        set -x
        echo "CICD_REPO_MGR_DIR=${GITHUB_WORKSPACE}/cicd-manager" >> ${GITHUB_ENV}
        echo "SYSTEM_DEFS_DIR=${GITHUB_WORKSPACE}/cicd-manager/.github/system-defs" >> ${GITHUB_ENV}
        set +x
    - id: clone-cicd-manager-repo
      name: clone-cicd-manager-repo
      uses: actions/checkout@v2
      with:
        ref: master
        path: ${{ env.CICD_REPO_MGR_DIR }}
    - id: parse-system-def
      name: parse-system-def
      run: |
        SYSTEM_DEFS_FILE=$(ls ${SYSTEM_DEFS_DIR}/${SYSTEM_NAME}.y*)
        TEST_ENVIRONMENTS=$(yq e '[.test-environments]' "${SYSTEM_DEFS_FILE}" -o json)
        echo "TEST_ENVIRONMENTS: ${TEST_ENVIRONMENTS}"
        echo ::set-output name=test-environments::$(echo ${TEST_ENVIRONMENTS})
    - id: build
      name: build
      run: |
        echo
        echo "building..."
    - id: test
      name: test
      run: |
        echo
        echo "testing..."
    - id: scan
      name: scan
      run: |
        echo
        echo "scanning..."
    - id: build-image
      name: build-image
      run: |
        echo
        echo "building image..."
    - id: scan-image
      name: scan-image
      run: |
        echo
        echo "scanning image..."
    - id: push-image
      name: push-image
      run: |
        echo
        echo "pushing image..."
  deploy-image-to-dev:
    if: matrix.environment == 'dev'
    runs-on: dev.mdw.nicks.world
    needs: build-test-scan-to-image
    strategy:
      max-parallel: 1
      matrix:
        environment: dev
    steps:
    - id: deploy
      name: deploy
      run: |
        echo
        echo "deploying to dev..."
    - id: verify-deployment
      name: verify-deployment
      run: |
        echo
        echo "verifying deployment in dev..."
    - id: publish-results
      name: publish-results
      run: |
        echo
        echo "publishing results for dev..."
  deploy-image-to-test:
    runs-on: test.mdw.nicks.world
    needs: [build-test-scan-to-image, deploy-image-to-dev]
    strategy:
      max-parallel: 1
      matrix:
        test-environment: ${{ fromJSON(needs.build-test-scan-to-image.outputs.test-environments) }}
    steps:
    - id: deploy
      name: deploy
      run: |
        echo
        echo "deploying to ${{ matrix.test-environment }}..."
    - id: verify-deployment
      name: verify-deployment
      run: |
        echo
        echo "verifying deployment in ${{ matrix.test-environment }}..."
    - id: publish-results
      name: publish-results
      run: |
        echo
        echo "publishing results for ${{ matrix.test-environment }}..."