name: build-from-source
on:
  workflow_call:
    inputs:
      system-name:
        required: true
        type: string
      team-name:
        required: true
        type: string
jobs:
  build-to-image:
    runs-on: ubuntu-latest
    env:
      SYSTEM_NAME: ${{ inputs.system-name }}
    steps:
    - id: setup-environment
      name: setup-environment
      uses: hippyod/cicd-manager/run-step@development
      with:
        label: infra
        step-name: setup-environment
    - id: clone-cicd-manager-repo
      name: clone-cicd-manager-repo
      uses: actions/checkout@v2
      with:
        repository: hippyod/cicd-manager
        ref: development
        path: ${{ env.CICD_REPO_MGR_DIR }}
    - id: parse-system-def
      name: parse-system-def
      uses: hippyod/cicd-manager/run-step@development
      with:
        label: infra
        step-name: parse-component-def
    - id: clone-app-repo
      name: clone-app-repo
      uses: actions/checkout@v2
      with:
        ref: development
        path: ${{ env.WORKING_DIR }}
    - id: build
      name: build
      uses: hippyod/cicd-manager/run-step@development
      with:
        label: ${{ env.CODEBASE }}
        step-name: build
    - id: test
      name: test
      uses: hippyod/cicd-manager/run-step@development
      with:
        label: ${{ env.CODEBASE }}
        step-name: test
    - id: scan
      name: scan
      uses: hippyod/cicd-manager/run-step@development
      with:
        label: ${{ env.CODEBASE }}
        step-name: scan
    - id: build-image
      name: build-image
      uses: hippyod/cicd-manager/run-step@development
      with:
        label: image
        step-name: build-image
    - id: scan-image
      name: scan-image
      uses: hippyod/cicd-manager/run-step@development
      with:
        label: image
        step-name: scan-image
    - id: push-image
      name: push-image
      uses: hippyod/cicd-manager/run-step@development
      with:
        label: image
        step-name: push-image