name: build-from-source
on:
  workflow_call:
    inputs:
      system-name:
        required: true
        type: string
jobs:
  build-to-image:
    runs-on: build.mdw.nicks.world
    env:
      SYSTEM_NAME: ${{ inputs.system-name }}
    steps:
    - id: setup-environment
      name: setup-environment
      run: |
        set -x
        echo "CICD_REPO_MGR_DIR=${GITHUB_WORKSPACE}/cicd-manager" >> ${GITHUB_ENV}
        echo "SYSTEM_DEFS_DIR=${GITHUB_WORKSPACE}/cicd-manager/.github/system-defs" >> ${GITHUB_ENV}
        echo "WORKING_DIR=${GITHUB_WORKSPACE}/${GITHUB_REPOSITORY}" >> ${GITHUB_ENV}
        set +x

        echo ::add-mask::$(cat /var/secrets/PAT_TOKEN)
        echo "PAT_TOKEN=$(cat /var/secrets/PAT_TOKEN)" >> ${GITHUB_ENV}
    - id: clone-cicd-manager-repo
      name: clone-cicd-manager-repo
      uses: actions/checkout@v2
      with:
        repository: nicks-world/cicd-manager
        ref: main
        path: ${{ env.CICD_REPO_MGR_DIR }}
        token: ${{ env.PAT_TOKEN }}
    - id: parse-system-def
      name: parse-system-def
      run: |
        SYSTEM_DEFS_FILE=$(ls ${SYSTEM_DEFS_DIR}/${SYSTEM_NAME}.y*)
        COMPONENT_NAME=$(basename ${WORKING_DIR})
        CODEBASE=$(yq e ".components[] | select(.repo == \"${COMPONENT_NAME}\") | .codebase" ${SYSTEM_DEFS_FILE})
        echo "CODEBASE: ${CODEBASE}"
        echo ::set-output name=codebase::$(echo ${CODEBASE})
    - id: clone-app-repo
      name: clone-app-repo
      uses: actions/checkout@v2
      with:
        ref: main
        path: ${{ env.WORKING_DIR }}
    - id: build
      name: build
      uses: nicks-world/cicd-manager/run-step@main
      with:
        label: ${{ steps.parse-system-def.outputs.codebase }}
        step-name: build
    - id: test
      name: test
      uses: nicks-world/cicd-manager/run-step@main
      with:
        label: ${{ steps.parse-system-def.outputs.codebase }}
        step-name: test
    - id: scan
      name: scan
      uses: nicks-world/cicd-manager/run-step@main
      with:
        label: ${{ steps.parse-system-def.outputs.codebase }}
        step-name: scan
    - id: build-image
      name: build-image
      uses: nicks-world/cicd-manager/run-step@main
      with:
        label: shared
        step-name: build-image
    - id: scan-image
      name: scan-image
      uses: nicks-world/cicd-manager/run-step@main
      with:
        label: shared
        step-name: scan-image
    - id: push-image
      name: push-image
      uses: nicks-world/cicd-manager/run-step@main
      with:
        label: shared
        step-name: push-image