name: build-and-deploy
on:
  workflow_call:
    inputs:
      env-to:
        required: false
        type: string
jobs:
  build-test-scan-to-image:
    outputs:
      matrix: ${{ steps.collect-envs.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
    - id: setup-environment
      name: setup-environment
      run: |
        set -x
        echo "CICD_REPO_MGR_DIR=${GITHUB_WORKSPACE}/cicd-poc-mgr" >> ${GITHUB_ENV}
        echo "SYSTEM_DEFS_DIR=${GITHUB_WORKSPACE}/cicd-poc-mgr/.github/system-defs" >> ${GITHUB_ENV}
        set +x
    - id: clone-cicd-manager-repo
      name: clone-cicd-manager-repo
      uses: actions/checkout@v2
      with:
        ref: master
        path: ${{ env.CICD_REPO_MGR_DIR }}
    - id: parse-system-def
      name: parse-system-def
      run: |
        SYSTEM_DEFS_FILE=$(ls ${SYSTEM_DEFS_DIR}/${SYSTEM_NAME}.y*)
        ENVIRONMENTS=$(yq e '[.environments]' "${SYSTEM_DEFS_FILE}" -o json)
        echo "ENVIRONMENTS: ${ENVIRONMENTS}"
        echo ::set-output name=matrix::$(echo ${ENVIRONMENTS})
    - id: build
      name: build
      run: |
        echo
        echo "building..."
    - id: test
      name: test
      run: |
        echo
        echo "testing..."
    - id: scan
      name: scan
      run: |
        echo
        echo "scanning..."
    - id: build-image
      name: build-image
      run: |
        echo
        echo "building image..."
    - id: scan-image
      name: scan-image
      run: |
        echo
        echo "scanning image..."
    - id: push-image
      name: push-image
      run: |
        echo
        echo "pushing image..."
  deploy-image:
    runs-on: ubuntu-latest
    needs: build-test-scan-to-image
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ fromJSON(needs.build-test-scan-to-image.outputs.matrix) }}
    steps:
    - id: deploy
      name: deploy
      run: |
        echo
        echo "deploying to ${{ matrix.environment }}..."
    - id: verify-deployment
      name: verify-deployment
      run: |
        echo
        echo "verifying deployment in ${{ matrix.environment }}..."
    - id: publish-results
      name: publish-results
      run: |
        echo
        echo "publishing results for ${{ matrix.environment }}..."