name: 'onboard-system'
on:
  workflow_dispatch:
    inputs:
      system-name:
        description: 'system-name: Name of the system to be onboarded and managed by the CICD system'
        required: true
jobs:
  gather-system-info:
    runs-on: ubuntu-latest
    steps:
    - id: setup-environment
      name: setup-environment
      run: |
        set -x
        echo "SYSTEM_NAME=${{ github.event.inputs.system-name }}" >> ${GITHUB_ENV}
        echo "CICD_REPO_MGR_DIR=${GITHUB_WORKSPACE}/${GITHUB_REPOSITORY}" >> ${GITHUB_ENV}
        echo "SYSTEM_DEFS_DIR=${GITHUB_WORKSPACE}/${GITHUB_REPOSITORY}/.github/system-defs" >> ${GITHUB_ENV}
        set +x
    - id: clone-cicd-manager-repo
      name: clone-cicd-manager-repo
      uses: actions/checkout@v2
      with:
        ref: master
        path: ${{ env.CICD_REPO_MGR_DIR }}
    - id: parse-system-def
      name: parse-system-def
      run: |
        SYSTEM_DEFS_FILE=$(ls ${SYSTEM_DEFS_DIR}/${SYSTEM_NAME}.y*)
        REPO_NAMES=$(yq e '[.organization + "/" + .components[].repo]' "${SYSTEM_DEFS_FILE}" -o json)
        echo "REPO_NAMES: ${REPO_NAMES}"
        echo ::set-output name=matrix::$(echo ${REPO_NAMES})
    outputs:
      matrix: ${{ steps.parse-system-def.outputs.matrix }}
      CICD_REPO_MGR_DIR: ${{ env.CICD_REPO_MGR_DIR }}
  onboard-system:
    runs-on: ubuntu-latest
    needs: gather-system-info
    env:
      CICD_REPO_MGR_DIR: ${{ needs.gather-system-info.outputs.CICD_REPO_MGR_DIR }}
    strategy:
      matrix:
        system-repo: ${{ fromJSON(needs.gather-system-info.outputs.matrix) }}
    steps:
      - id: setup-environment
        name: setup-environment
        run: |
          set -x
          echo "WORKING_DIR=${GITHUB_WORKSPACE}/${{ matrix.system-repo }}" >> ${GITHUB_ENV}
          set +x
      - id: clone-cicd-manager-repo
        name: clone-cicd-manager-repo
        uses: actions/checkout@v2
        with:
          ref: master
          path: ${{ env.CICD_REPO_MGR_DIR }}
      - id: clone-app-repo
        name: clone-app-repo
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.system-repo }}
          ref: master
          path: ${{ env.WORKING_DIR }}
          token: ${{ secrets.CICD_TOKEN }}
      - id: install-github-workflow-directory
        name: install-github-workflow-directory
        run: |
          set -x
          rm -rf ${WORKING_DIR}/.github
          cp -R ${CICD_REPO_MGR_DIR}/.github-app-template ${WORKING_DIR}/.github
          if [[ ! -z "$(git -C ${WORKING_DIR} status --porcelain)" ]]
          then
              git -C ${WORKING_DIR} config user.email ${cicd-team@my-org.com}
              git -C ${WORKING_DIR} config user.name ${GITHUB_ACTOR}
              git -C ${WORKING_DIR} add -A 
              git -C ${WORKING_DIR} commit -am 'installing latest cicd-poc-mgr GitHub Action Workflow(s)'
              git -C ${WORKING_DIR} push
          else
              echo "${{ matrix.system-repo }} is unchanged.  Skipping..."
          fi
          set +x
